// Code generated by Prismic. DO NOT EDIT.

import BentoFeatures from "./BentoFeatures";
import BlogShowcase from "./BlogShowcase";
import CallToAction from "./CallToAction";
import DataFlows from "./DataFlows";
import Faq from "./Faq";
import FeatureShowcase from "./FeatureShowcase";
import FeaturesGrid from "./FeaturesGrid";
import Hero from "./Hero";
import PlatformDownload from "./PlatformDownload";
import Principles from "./Principles";
import PrivacyComparison from "./PrivacyComparison";
import SetupSteps from "./SetupSteps";
import StatsShowcase from "./StatsShowcase";
import Testimonials from "./Testimonials";

export const components = {
  bento_features: BentoFeatures,
  blog_showcase: BlogShowcase,
  call_to_action: CallToAction,
  data_flows: DataFlows,
  faq: Faq,
  feature_showcase: FeatureShowcase,
  features_grid: FeaturesGrid,
  hero: Hero,
  platform_download: PlatformDownload,
  principles: Principles,
  privacy_comparison: PrivacyComparison,
  setup_steps: SetupSteps,
  stats_showcase: StatsShowcase,
  testimonials: Testimonials,
};
